
all:
	mkdir -p bin js
	cp lwasm/lwasm bin/lwasm.bc
	cp lwlink/lwlink bin/lwlink.bc
	make -f Makefile.emcc js/lwasm.js js/lwlink.js

js/%.js: bin/%.bc
	emcc -O2 --memory-init-file 0 \
	-s MODULARIZE=1 \
	-s EXPORT_NAME=\"'$*'\" \
	-s 'EXTRA_EXPORTED_RUNTIME_METHODS=["FS","callMain"]' \
	-s FORCE_FILESYSTEM=1 \
	bin/$*.bc -o $@ $(ARGS_$*)
